language: ruby

rvm:
 - 2.3.8
 - 2.4.6
 - 2.5.5
 - 2.6.3

gemfile:
  - gemfiles/Gemfile-rails-4-0
  - gemfiles/Gemfile-rails-4-1
  - gemfiles/Gemfile-rails-4-2
  - gemfiles/Gemfile-rails-5-0
  - gemfiles/Gemfile-rails-5-1
  - gemfiles/Gemfile-rails-5-2
  - gemfiles/Gemfile-rails-6-0
  - gemfiles/Gemfile-sprockets-2-11
  - gemfiles/Gemfile-sprockets-2-12
  - gemfiles/Gemfile-sprockets-2-8
  - gemfiles/Gemfile-sprockets-3-0
  - gemfiles/Gemfile-sprockets-4-0
  - gemfiles/Gemfile-sprockets-rails-2-2
  - gemfiles/Gemfile-sprockets-rails-master
  - gemfiles/Gemfile-sass-3-1
  - gemfiles/Gemfile-sass-3-2
  - gemfiles/Gemfile-sass-3-3
  - gemfiles/Gemfile-sass-3-4

sudo: false

cache: bundler

script: bundle exec rake test

matrix:
  exclude:
  include:
    - gemfile: Gemfile
      rvm: 2.5.5
    - gemfile: Gemfile
      rvm: 2.6.3

notifications:
  email: false
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.org#rails-contrib"
  campfire:
    on_success: change
    on_failure: always
    rooms:
      - secure: "CGWvthGkBKNnTnk9YSmf9AXKoiRI33fCl5D3jU4nx3cOPu6kv2R9nMjt9EAo\nOuS4Q85qNSf4VNQ2cUPNiNYSWQ+XiTfivKvDUw/QW9r1FejYyeWarMsSBWA+\n0fADjF1M2dkDIVLgYPfwoXEv7l+j654F1KLKB69F0F/netwP9CQ="
